---
title: "lab Azure"
output:
  distill::distill_article:
    toc: true
    toc_depth: 1
---

```{r}
library(knitr)
library(dplyr)
library(ggpubr)
library(kableExtra)
library(rmarkdown)
library(stringr)
```

```{r}
load("USERS.RData")
USERS$NOME <- str_split(as.character(USERS$NAME), " ", simplify = TRUE)[,1]
USERS$COGNOME <- str_split(as.character(USERS$NAME), " ", n=2, simplify = TRUE)[,2]
USERS$POS[17]<-"external"
USERS$POS[19]<-"external"
```


# Groups

| Economics | Statistics | Projects |
|----------|------------|----------|
| [de-as101](de-as101.html) | [ds-cl101](ds-cl101.html) | [fs-eu110](fs-eu110.html) |
| [de-cb101](de-cb101.html) | [ds-mb101](ds-mb101.html) | [le-am101](le-am101.html) |
| [de-tm101](de-tm101.html) | [ds-mp101](ds-mp101.html) | [cs-ux110](cs-ux110.html) |
| [de-pt101](de-pt101.html) | [ds-ac101](ds-ac101.html) |  |
| [ds-ab101](ds-ab101.html) | [ds-rb101](ds-rb101.html) |  |
| | [ds-mb100](ds-mb100.html) |  |

# List of users

```{r}
usrs = filter(USERS) %>% select("COGNOME","NOME", "POS", "ROLE", "GROUP") %>% arrange(POS,COGNOME)
paged_table(usrs)
```

# Admin

Giovanni Pelosi

| Sistemi |
|--|
| mn-si501 | 
| xt-si701 | 
| xt-si601 |



